---
docker-credentials: &docker-credentials
  username: ((ce-dockerhub-id))
  password: ((ce-dockerhub-token))

resource_types:
  - name: meta
    type: docker-image
    source:
      repository: swce/metadata-resource
      <<: *docker-credentials

resources:
  - name: meta
    type: meta
  
  - name: python3-base
    type: docker-image
    source:
      repository: openstax/python3-base
      <<: *docker-credentials

  - name: python3-poetry
    type: docker-image
    source:
      repository: openstax/python-poetry
      <<: *docker-credentials

  - name: python-base-dockerfile
    type: git
    source:
      uri: https://github.com/openstax/ce-images.git
      branch: main
      paths:
        - python/Dockerfile
  
  - name: python-poetry-dockerfile
    type: git
    source:
      uri: https://github.com/openstax/ce-images.git
      branch: main
      paths:
        - poetry/Dockerfile
jobs:
  - name: build-publish-python-base
    plan:
      - get: meta
      - get: python-base-dockerfile
        trigger: true
      - task: generate-timestamp-tag
        file: python-base-dockerfile/.concourse/tasks/generate-tag/task.yml
      - put: python3-base
        params:
          build: python-base-dockerfile/python
          tag_file: generated-tag/TAG
          tag_as_latest: true
  
  - name: build-publish-python-poetry
    plan:
      - get: meta
      - get: python-poetry-dockerfile
        trigger: true
      - task: generate-timestamp-tag
        file: python-poetry-dockerfile/.concourse/tasks/generate-tag/task.yml
      - put: python3-poetry
        params:
          build: python-poetry-dockerfile/poetry
          tag_file: generated-tag/TAG
          tag_as_latest: true
