---
docker-credentials: &docker-credentials
  username: ((ce-dockerhub-id))
  password: ((ce-dockerhub-token))

ecr-credentials: &ecr-credentials
  aws_secret_access_key: ((ce_ecr_user_access_key))
  aws_access_key_id: ((ce_ecr_user_access_key_id))

resource_types:
  - name: meta
    type: docker-image
    source:
      repository: swce/metadata-resource
      <<: *docker-credentials

resources:
  - name: meta
    type: meta
  
  - name: python3-base-ecr
    type: docker-image
    source:
      repository: 258998078732.dkr.ecr.us-east-2.amazonaws.com/python3-base
      <<: *ecr-credentials
  
  - name: python3-base-docker
    type: docker-image
    source:
      repository: openstax/python3-base
      <<: *docker-credentials

  - name: python3-poetry-ecr
    type: docker-image
    source:
      repository: 258998078732.dkr.ecr.us-east-2.amazonaws.com/python3-poetry
      <<: *ecr-credentials

  - name: python3-poetry-docker
    type: docker-image
    source:
      repository: openstax/python3-poetry
      <<: *docker-credentials
  
  - name: python3-chrome-docker
    type: docker-image
    source:
      repository: openstax/python3-chrome-base
      <<: *docker-credentials
  
  - name: python3-chrome-debug-docker
    type: docker-image
    source:
      repository: openstax/python3-chrome-debug
      <<: *docker-credentials

  - name: python-base-dockerfile
    type: git
    source:
      uri: https://github.com/openstax/ce-images.git
      branch: main
      paths:
        - python/Dockerfile
  
  - name: python-poetry-dockerfile
    type: git
    source:
      uri: https://github.com/openstax/ce-images.git
      branch: main
      paths:
        - poetry/Dockerfile
  
  - name: python3-chrome-dockerfile
    type: git
    source:
      uri: https://github.com/openstax/ce-images.git
      branch: main
      paths:
        - chrome/Dockerfile
  
  - name: python3-chrome-debug-dockerfile
    type: git
    source:
      uri: https://github.com/openstax/ce-images.git
      branch: main
      paths:
        - chrome-debug/Dockerfile
jobs:
  - name: build-publish-python-base
    plan:
      - get: meta
      - get: python-base-dockerfile
        trigger: true
      - task: generate-timestamp-tag
        file: python-base-dockerfile/.concourse/tasks/generate-tag/task.yml
      - put: python3-base-ecr
        params:
          build: python-base-dockerfile/python
          tag_file: generated-tag/TAG
          tag_as_latest: true
      - put: python3-base-docker
        params:
          build: python-base-dockerfile/python
          tag_file: generated-tag/TAG
          tag_as_latest: true

  - name: build-publish-python-poetry
    plan:
      - get: meta
      - get: python-base-dockerfile
        trigger: true
        passed: [build-publish-python-base]
      - get: python-poetry-dockerfile
        trigger: true
      - task: generate-timestamp-tag
        file: python-poetry-dockerfile/.concourse/tasks/generate-tag/task.yml
      - put: python3-poetry-ecr
        params:
          build: python-poetry-dockerfile/poetry
          tag_file: generated-tag/TAG
          tag_as_latest: true
      - put: python3-poetry-docker
        params:
          build: python-poetry-dockerfile/poetry
          tag_file: generated-tag/TAG
          tag_as_latest: true

  - name: build-publish-python3-chrome
    plan:
      - get: meta
      - get: python-base-dockerfile
        trigger: true
        passed: [build-publish-python-base]
      - get: python3-chrome-dockerfile
        trigger: true
      - task: generate-timestamp-tag
        file: python3-chrome-dockerfile/.concourse/tasks/generate-tag/task.yml
      - put: python3-chrome-docker
        params:
          build: python3-chrome-dockerfile/chrome
          tag_file: generated-tag/TAG
          tag_as_latest: true
  
  - name: build-publish-python3-chrome-debug
    plan:
      - get: meta
      - get: python-base-dockerfile
        trigger: true
        passed: [build-publish-python3-chrome]
      - get: python3-chrome-debug-dockerfile
        trigger: true
      - task: generate-timestamp-tag
        file: python3-chrome-debug-dockerfile/.concourse/tasks/generate-tag/task.yml
      - put: python3-chrome-debug-docker
        params:
          build: python3-chrome-debug-dockerfile/chrome-debug
          tag_file: generated-tag/TAG
          tag_as_latest: true
